### ISSUE TITLE
Lab: Voice Data Build your data set - Step 3: Create .json file ERROR

### ISSUE THREAD

**Issue by cpark-dev** [udacity/aind-issue-reports#141]
Term2. 
5. Voice User Interfaces
Lesson7. Introduction to Speech Recognition
13. Lab: Voice Data
Build your data set - Step 3: Create .json file needed for processing

filename: [udacity/AIND-VUI-Lab-Voice-Data/create_desc_json.py](https://github.com/udacity/AIND-VUI-Lab-Voice-Data/blob/master/create_desc_json.py)

=> I got an error like below: 
```
chanhopark (master *) AIND-VUI-Lab-Voice-Data $ python create_desc_json.py MySpeech/my_dev my_dev.json
Traceback (most recent call last):
  File "create_desc_json.py", line 55, in <module>
    main(args.data_directory, args.output_file)
  File "create_desc_json.py", line 25, in main
    for speaker in os.listdir(speaker_path):
NotADirectoryError: [Errno 20] Not a directory: 'MySpeech/my_dev/.DS_Store'
```

So, I add if statements not to deal with hidden files. 

My solution is 
```
def main(data_directory, output_file):
    labels = []
    durations = []
    keys = []
    for group in os.listdir(data_directory):
        if not group.startswith('.'):        <= Add this line
            speaker_path = os.path.join(data_directory, group)
            for speaker in os.listdir(speaker_path):
                if not speaker.startswith('.'):          <= Add this line
                    labels_file = os.path.join(speaker_path, speaker,
                                               '{}-{}.trans.txt'
                                               .format(group, speaker))
```

**Comment by cgearhart** [comment]
Internal ticket #J1913
