### ISSUE TITLE
conda env create -f environment.yml throws a syntax error

### ISSUE THREAD

**Issue by lgandras** [udacity/aind-issue-reports#229]
Hi, regarding the `aind-universal.yml` provided: https://d17h27t6h515a5.cloudfront.net/topher/2018/January/5a5817f5_aind-universal/aind-universal.yml. The error i get is actually "Invalid requirement, parse error at "'- udacit'"". It seems it doesn't like the dashes in the conda file. If I install the packages via:
```
pip install z3-solver udacity-pa hmmlearn
```
I get no errors whatsoever. The reason I noticed is becase *udacity-pa* isn't getting installed either through the environment file.

**Comment by lgandras** [comment]
Here's the console output:
```
Invalid requirement: 'hmmlearn==0.2.0 - udacity-pa>=0.2 - z3-solver'
Traceback (most recent call last):
  File "/home/andras/.anaconda3/envs/aind/lib/python3.5/site-packages/pip/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/home/andras/.anaconda3/envs/aind/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/home/andras/.anaconda3/envs/aind/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/andras/.anaconda3/envs/aind/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/andras/.anaconda3/envs/aind/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/andras/.anaconda3/envs/aind/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/andras/.anaconda3/envs/aind/lib/python3.5/site-packages/pip/_vendor/pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 16), (line:1, col:17)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/andras/.anaconda3/envs/aind/lib/python3.5/site-packages/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/home/andras/.anaconda3/envs/aind/lib/python3.5/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'- udacit'"
CondaValueError: pip returned an error.
```

**Comment by lgandras** [comment]
OS: Ubuntu 16.04.4 LTS 
Conda installation file: Anaconda3-5.0.1-Linux-x86_64.sh
