### ISSUE TITLE
Term 2 Lesson 2 Item 30 Keras explanation doesn't correspond to code(?)

### ISSUE THREAD

**Issue by letyrodridc** [udacity/aind-issue-reports#95]
It says: "The first layer from above, model.add(Flatten(input_dim=32)),"

But the code is : 
#1st Layer - Add an input layer of 32 nodes
    model.add(Dense, input_dim=32)

**Comment by timrross** [comment]
I can confirm the description is still not correct, and doesn't correspond to the demo code. 

Also when I try the new tricks suggestion, I'get an error.

```
# Building the model
xor = Sequential()
# Hint: This next line is where you can change the size of the first hidden layer, it's current size is 8
xor.add(Dense(4, input_dim=2))
# Hint: This next line is where you can change the activation funcion to "relu"
xor.add(Activation("relu"))
```

Results in this: 

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "vm_main3.py", line 47, in <module>
    import main
  File "/tmp/vmuser_spluujwnfw/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_spluujwnfw/studentMain.py", line 7, in <module>
    prevent_tf_error()
  File "/tmp/vmuser_spluujwnfw/studentMain.py", line 5, in prevent_tf_error
    import network
  File "/tmp/vmuser_spluujwnfw/network.py", line 34, in <module>
    history = xor.fit(X, y, nb_epoch=100, verbose=0)
  File "/usr/local/lib/python3.4/dist-packages/keras/models.py", line 672, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 1116, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 1033, in _standardize_user_data
    exception_prefix='model target')
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 124, in standardize_input_data
    str(array.shape))
ValueError: Error when checking model target: expected dense_1 to have shape (None, 4) but got array with shape (4, 2)

```

**Comment by cgearhart** [comment]
Reworked that example to fix these issues.
